import { afterAll, describe, expect, test } from 'bun:test'
import { spawnSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { lstatSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, readlinkSync, rmSync, symlinkSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { runDoctor } from '../../doctor.ts'
import { inspectRepository } from './repo.ts'
import { inspectUser } from './user.ts'

const here = dirname(fileURLToPath(import.meta.url))
const harness = resolve(here, '../../../../../..')
const bootstrap = resolve(here, '../repo-bootstrap/repo-bootstrap.ts')
const userInstall = resolve(here, '../user-install/user-install.ts')
const roots: string[] = []
const CONFIG = '[ki-repo]\nsupported_runtimes = ["claude-code"]\n\n[ki-authoring]\n'

function fixture(prefix: string): string {
  const root = mkdtempSync(join(tmpdir(), prefix))
  roots.push(root)
  return root
}

function snapshot(root: string): string {
  const rows: string[] = []
  const walk = (path: string, rel: string): void => {
    const entry = lstatSync(path)
    if (entry.isSymbolicLink()) rows.push(`l ${rel} ${entry.mode & 0o7777} ${readlinkSync(path)}`)
    else if (entry.isDirectory()) {
      rows.push(`d ${rel} ${entry.mode & 0o7777}`)
      for (const name of readdirSync(path).sort()) walk(join(path, name), rel ? join(rel, name) : name)
    } else if (entry.isFile()) rows.push(`f ${rel} ${entry.mode & 0o7777} ${createHash('sha256').update(readFileSync(path)).digest('hex')}`)
    else rows.push(`o ${rel} ${entry.mode & 0o7777}`)
  }
  walk(root, '.')
  return rows.join('\n')
}

function bootstrappedRepo(): string {
  const root = fixture('ki-doctor-repo-')
  writeFileSync(join(root, '.ki-config.toml'), CONFIG)
  const result = spawnSync('bun', [bootstrap, root], { cwd: harness, encoding: 'utf8' })
  if (result.status !== 0) throw new Error(`fixture bootstrap failed: ${result.stderr}`)
  return root
}

function installedHome(): string {
  const home = fixture('ki-doctor-user-')
  mkdirSync(join(home, '.claude'))
  const result = spawnSync(
    'bun',
    [
      userInstall,
      '--source',
      join(harness, 'skills'),
      '--hooks-source',
      join(harness, 'hooks'),
      '--home',
      home,
      '--runtime',
      'claude-code'
    ],
    { cwd: harness, encoding: 'utf8' }
  )
  if (result.status !== 0) throw new Error(`fixture user install failed: ${result.stderr}`)
  return home
}

afterAll(() => {
  for (const root of roots) rmSync(root, { recursive: true, force: true })
})

describe('repository DOCTOR', () => {
  test('classifies absent adoption and never writes', () => {
    const root = fixture('ki-doctor-absent-')
    const before = snapshot(root)
    expect(inspectRepository(root)).toMatchObject({ schema: 1, scope: 'repo', status: 'absent', action: 'none', exit: 0 })
    expect(snapshot(root)).toBe(before)
  })

  test('routes a declared repo with no generated state to EDUCATE without writing', () => {
    const root = fixture('ki-doctor-recoverable-')
    writeFileSync(join(root, '.ki-config.toml'), CONFIG)
    const before = snapshot(root)
    expect(inspectRepository(root)).toMatchObject({ status: 'recoverable', action: 'educate', exit: 1 })
    expect(snapshot(root)).toBe(before)
  })

  test('recognises a healthy ownership-proven repository without writing', () => {
    const root = bootstrappedRepo()
    const before = snapshot(root)
    expect(inspectRepository(root)).toMatchObject({ status: 'healthy', action: 'none', exit: 0 })
    expect(snapshot(root)).toBe(before)
  })

  test('routes missing runtime projection through CLEAN without writing', () => {
    const root = bootstrappedRepo()
    rmSync(join(root, '.claude', 'skills', 'ki-authoring'), { recursive: true })
    const before = snapshot(root)
    expect(inspectRepository(root)).toMatchObject({ status: 'recoverable', action: 'clean', exit: 1 })
    expect(snapshot(root)).toBe(before)
  })

  test('routes orphaned proven runtime state through CLEAN without writing', () => {
    const root = bootstrappedRepo()
    rmSync(join(root, '.ki', 'bin'), { recursive: true })
    rmSync(join(root, '.ki', 'bootstrap'), { recursive: true })
    rmSync(join(root, '.ki', 'manifest.json'))
    const before = snapshot(root)
    expect(inspectRepository(root)).toMatchObject({ status: 'recoverable', action: 'clean', exit: 1 })
    expect(snapshot(root)).toBe(before)
  })

  test('classifies altered generated bytes as unsafe without writing', () => {
    const root = bootstrappedRepo()
    const audit = join(root, '.ki', 'bin', 'ki-audit')
    writeFileSync(audit, `${readFileSync(audit, 'utf8')}\nchanged\n`)
    const before = snapshot(root)
    expect(inspectRepository(root)).toMatchObject({ status: 'unsafe', action: 'manual-reconciliation', exit: 1 })
    expect(snapshot(root)).toBe(before)
  })

  test('rejects a linked declaration and leaves its target untouched', () => {
    const root = fixture('ki-doctor-linked-')
    const outside = fixture('ki-doctor-outside-')
    const declaration = join(outside, 'config.toml')
    writeFileSync(declaration, CONFIG)
    symlinkSync(declaration, join(root, '.ki-config.toml'))
    const beforeRoot = snapshot(root)
    const beforeOutside = snapshot(outside)
    expect(inspectRepository(root)).toMatchObject({ status: 'unsafe', action: 'manual-reconciliation' })
    expect(snapshot(root)).toBe(beforeRoot)
    expect(snapshot(outside)).toBe(beforeOutside)
  })

  test('rejects a linked runtime parent and leaves its target untouched', () => {
    const root = bootstrappedRepo()
    const outside = fixture('ki-doctor-runtime-outside-')
    const runtime = join(root, '.claude')
    rmSync(runtime, { recursive: true })
    mkdirSync(join(outside, 'skills'), { recursive: true })
    symlinkSync(outside, runtime)
    const beforeRoot = snapshot(root)
    const beforeOutside = snapshot(outside)
    expect(inspectRepository(root)).toMatchObject({ status: 'unsafe', action: 'manual-reconciliation' })
    expect(snapshot(root)).toBe(beforeRoot)
    expect(snapshot(outside)).toBe(beforeOutside)
  })
})

describe('user DOCTOR', () => {
  test('classifies absent managed user state without scanning repositories', () => {
    const home = fixture('ki-doctor-user-absent-')
    mkdirSync(join(home, 'work', 'repo'), { recursive: true })
    writeFileSync(join(home, 'work', 'repo', '.ki-config.toml'), CONFIG)
    const before = snapshot(home)
    expect(inspectUser(home)).toMatchObject({ schema: 1, scope: 'user', status: 'absent', action: 'none', exit: 0 })
    expect(snapshot(home)).toBe(before)
  })

  test('recognises healthy managed user state without writing', () => {
    const home = installedHome()
    const before = snapshot(home)
    expect(inspectUser(home, ['claude-code'])).toMatchObject({ status: 'healthy', action: 'none', exit: 0 })
    expect(snapshot(home)).toBe(before)
  })

  test('routes an incomplete but proven installation to scoped user UNINSTALL', () => {
    const home = installedHome()
    rmSync(join(home, '.claude', 'skills', 'ki-recap'), { recursive: true })
    const before = snapshot(home)
    expect(inspectUser(home, ['claude-code'])).toMatchObject({ status: 'recoverable', action: 'user-uninstall', exit: 1 })
    expect(snapshot(home)).toBe(before)
  })

  test('routes an orphaned proven hook namespace to scoped user UNINSTALL', () => {
    const home = installedHome()
    rmSync(join(home, '.claude', 'skills'), { recursive: true })
    const before = snapshot(home)
    expect(inspectUser(home, ['claude-code'])).toMatchObject({ status: 'recoverable', action: 'user-uninstall', exit: 1 })
    expect(snapshot(home)).toBe(before)
  })

  test('classifies an altered managed skill as unsafe without writing', () => {
    const home = installedHome()
    const skill = join(home, '.claude', 'skills', 'ki-next', 'SKILL.md')
    writeFileSync(skill, `${readFileSync(skill, 'utf8')}\nchanged\n`)
    const before = snapshot(home)
    expect(inspectUser(home, ['claude-code'])).toMatchObject({ status: 'unsafe', action: 'manual-reconciliation', exit: 1 })
    expect(snapshot(home)).toBe(before)
  })

  test('rejects a linked runtime parent and leaves its target untouched', () => {
    const home = installedHome()
    const outside = fixture('ki-doctor-user-runtime-outside-')
    const runtime = join(home, '.claude', 'skills')
    rmSync(runtime, { recursive: true })
    mkdirSync(join(outside, 'skills'), { recursive: true })
    symlinkSync(join(outside, 'skills'), runtime)
    const beforeHome = snapshot(home)
    const beforeOutside = snapshot(outside)
    expect(inspectUser(home, ['claude-code'])).toMatchObject({ status: 'unsafe', action: 'manual-reconciliation' })
    expect(snapshot(home)).toBe(beforeHome)
    expect(snapshot(outside)).toBe(beforeOutside)
  })
})

describe('DOCTOR command contract', () => {
  test('requires explicit scope and emits stable JSON', () => {
    expect(() => runDoctor([], () => undefined)).toThrow('explicit scope')
    const root = fixture('ki-doctor-command-')
    let output = ''
    expect(runDoctor(['repo', root, '--format', 'json'], (value) => (output += value))).toBe(0)
    expect(JSON.parse(output)).toMatchObject({ schema: 1, scope: 'repo', status: 'absent', action: 'none', exit: 0 })
  })
})
