import type { ConformOutcome, RubricItem, RubricOutcomes } from '../../vendored/ki-skills/rubric.ts'
import type { WebsiteContext } from '../contexts/website.ts'
import { inactive, judgment, mechanical } from './shared.ts'

const conformDist = (c: WebsiteContext): RubricOutcomes<ConformOutcome> => {
  if (!c.available) return [{ status: 'VIOLATION', message: `target path is not a directory: ${c.target}` }]
  const result = c.ensureDistIgnore()
  return [
    {
      status: result === 'canonical' ? 'PASS' : result === 'fixed' ? 'FIXED' : 'NOT_APPLICABLE',
      message:
        result === 'canonical'
          ? `${c.siteRoot ? 'site/dist/' : 'dist/'} already correctly gitignored`
          : result === 'fixed'
            ? `${c.dryRun ? 'would ensure' : 'ensured'} the correct dist ignore entry`
            : 'no eleventy.config.* found — cannot derive the correct dist ignore; add it once the site layout exists',
      subject: '.gitignore'
    }
  ]
}
const auditDist = (c: WebsiteContext) => {
  const stop = inactive(c)
  if (stop) return stop
  const text = c.read('.gitignore')
  const correct = c.siteRoot ? /^\s*\/?site\/dist\/?\s*$/m.test(text) : /^\s*\/?dist\/?\s*$/m.test(text)
  const misplaced = c.siteRoot && /^\s*\/dist\/?\s*$/m.test(text)
  return [
    {
      status: correct ? 'PASS' : 'VIOLATION',
      ...(misplaced ? { level: 'FAIL' as const } : {}),
      message: correct
        ? `${c.siteRoot ? 'site/dist/' : 'dist/'} is correctly gitignored`
        : misplaced
          ? 'gitignore has /dist (repo root) but site/ layout puts output at site/dist/ — update to /site/dist'
          : `${c.siteRoot ? 'site/dist/' : 'dist/'} not found in .gitignore (build output should not be committed)`,
      subject: '.gitignore'
    }
  ]
}
export const WEB_33: RubricItem<WebsiteContext> = {
  ...mechanical(
    'WEB-33',
    'dist ignore',
    '`site/dist/` is gitignored (entry in `site/.gitignore` or as `site/dist/` from the repo root).',
    'FAIL',
    auditDist
  ),
  mechanical: { level: 'FAIL', audit: { phase: 'INSPECT', run: auditDist }, conform: { phase: 'NORMALISE', run: conformDist } }
}
export const WEB_34 = judgment(
  'WEB-34',
  'portable generated links',
  'the build emits relative internal links (the §4 transform actually fires over `.html`), so `dist/` serves from any root.',
  'Does the built HTML actually contain portable relative internal links?'
)
export const WEB_35 = judgment(
  'WEB-35',
  'generated dist boundary',
  '`dist/` is never hand-edited; it is fully regenerated by the build.',
  'Is dist treated as fully generated build output and never hand-edited?'
)
export const WEB_36 = mechanical(
  'WEB-36',
  'hosting assets directory seam',
  '`assets.directory` in `site/wrangler.jsonc` is `"dist"`/`"./dist"` (pointing at `site/dist/`) — a misplaced `"../dist"` is FAIL; verified in full by `ki-website-cloudflare`, named here as the seam.',
  'WARN',
  (c) => {
    const stop = inactive(c)
    if (stop) return stop
    if (!c.siteRoot) return [{ status: 'NOT_APPLICABLE', message: 'site/ workspace is absent' }]
    const path = c.has('site', 'wrangler.jsonc') ? 'site/wrangler.jsonc' : 'site/wrangler.json'
    const content = c.read(path)
    if (!content) return [{ status: 'NOT_APPLICABLE', message: 'no site wrangler configuration found' }]
    const directory = /"directory"\s*:\s*"([^"]+)"/.exec(content)?.[1]
    return [
      {
        status: directory === 'dist' || directory === './dist' ? 'PASS' : 'VIOLATION',
        ...(directory === '../dist' ? { level: 'FAIL' as const } : {}),
        message:
          directory === undefined
            ? 'wrangler.jsonc present but no assets.directory found'
            : directory === 'dist' || directory === './dist'
              ? `wrangler.jsonc assets.directory = "${directory}" (correct — site/dist/)`
              : directory === '../dist'
                ? 'wrangler.jsonc assets.directory = "../dist" (points to $root/dist/ — change to "dist")'
                : `wrangler.jsonc assets.directory = "${directory}" (unexpected value)`,
        subject: path
      }
    ]
  },
  { overrideLevels: ['FAIL'] }
)
export const DIST: readonly RubricItem<WebsiteContext>[] = [WEB_33, WEB_34, WEB_35, WEB_36]
